server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Enable React Router to handle all frontend routing
        try_files $uri $uri/ /index.html;
    }
}
